services:
  food-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food_classifier_api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - HF_REPO_ID=jamus0702/vn_food_classification
      - HF_FILENAME=v10_balanced_cpu.pkl
      - HF_HOME=/tmp/hf
      # - HF_TOKEN=hf_xxx   # chỉ cần nếu repo private
    restart: unless-stopped
